### ISSUE TITLE
How do I run the client?

### ISSUE THREAD

**Issue by MKwareContributions** [real-pmein1/stmsrvemu#23]
The emulator.exe have started just fine, but when I run Steam.exe in /client/ dir it errors with:

`Unable to load library Steam.dll`

I've tried copying Steam.exe from old version, it stucks at trying to download files.

**Comment by real-pmein1** [comment]
Please provide more info, like the debug log or console output

**Comment by CombineSoldier14** [comment]
Having the same issue. I copied over more files and steam.exe seems to work fine now but it gets stuck with an error when I finish making an account

**Comment by supervitu64** [comment]
you gotta move the client to a different folder, if it doesn't work you may need to delete everything, unzip the emulator again and rerun it

**Comment by real-pmein1** [comment]
Old issue with no updates from OP.
