### ISSUE TITLE
Finding manifests/storages to download games

### ISSUE THREAD

**Issue by nthclick** [real-pmein1/stmsrvemu#26]
I remember the discord contained a lot of links or downloads for manifests and storages in order to download games. However I left a while back while cleaning out my discord server list and seeing as (from the looks of the cs.rin.ru thread) that it is invite only I obviously can't access them anymore. I've tried searching far and wide on the internet for links containing storages however I can't find anything at all.

I also saw on the cs.rin.ru thread that "[storages are unavailable at this time](https://cs.rin.ru/forum/viewtopic.php?f=29&t=120040&start=495)". If so, what happened to them?

**Comment by Tempnology** [comment]
The storages for games are not provided unfortunately because theres some legal issues in regards due to them being game files. sorry :/

**Comment by shefben** [comment]
They can, however, if you manage to get your hands on GCF files; can be put in the files/convert/ folder and then it will convert the gcf to the storage format.  but a gcf only contains a single version of a game and it MUST be 100% validated/downloaded for the converter to work
