### ISSUE TITLE
file locked

### ISSUE THREAD

**Issue by icramox1** [real-pmein1/stmsrvemu#27]
what is the password of the file
?? i opened up but its locked

**Comment by CrazyCSIW6** [comment]
is lil bro retarded?

**Comment by Hellist** [comment]
I might be too late but just in case someone else sees this: cs.rin.ru

**Comment by icramox1** [comment]
> you can just download src

where can i download

**Comment by real-pmein1** [comment]
You can always download the source code in the releases section: https://github.com/real-pmein1/stmsrvemu/releases/
