### ISSUE TITLE
Where to find other clients, manifests, etc?

### ISSUE THREAD

**Issue by SHUTDOWNOfficial** [real-pmein1/stmsrvemu#28]
Hello! This project references certain things like "Dormine's v0.1 or v0.2 server" which from a cursory search on cs.rin.ru seems to not exist. The cs.rin.ru thread for this project also references many different versions of the Steam client, which I'm also having trouble finding. 
As I understand you've been working with Steam emulators for well over a decade now, and probably have a lot of old files that don't exist anywhere else, considering how many filehosts have gone down over the years.
Is there some place I'm missing that archives all of this stuff? Because it would be a really big shame for it to get lost to time, lol.

**Comment by okamitime** [comment]
It is hard to find much of the material that is referenced in this project's thread but quite a few of them are actually still available on the forum! Here is a thread on Dormine's server emulator: viewtopic.php?f=20&t=43826
And here is a thread which contains many valuable files for this project, including all three versions of Dormine's emulator (steam_content_emu_poc): viewtopic.php?f=14&t=90419

**Comment by supervitu64** [comment]
> viewtopic.php?f=20&t=43826

okaimi may i ask what the website does this link belong to?

**Comment by okamitime** [comment]
That is a partial link to a cs.rin.ru forum post, I'm unsure if we're permitted to post direct links so I only pasted part of the link.

**Comment by supervitu64** [comment]
oh thanks
