### ISSUE TITLE
Windows XP?

### ISSUE THREAD

**Issue by Valhisir** [real-pmein1/stmsrvemu#29]
Not sure if I'm doing something wrong, but Windows XP tells me it can't open the program.

**Comment by supervitu64** [comment]
you'll need a separate computer to run the steam emulator
on the different computer extract the emulator and change the server ip on the conf file so it matches your server pc's ip. after that, start the server. allow it to go thru firewall and let it prepare a client. move that client to a storage medium and use it on the windows XP PC

**Comment by supervitu64** [comment]
adding games n shii is more complicated so i cant help you with that

**Comment by real-pmein1** [comment]
XP is not a supported OS to run the emulator on.  Please use Win7 or higher.
