### ISSUE TITLE
how to properly use the emulator (on 2 different machines)

### ISSUE THREAD

**Issue by supervitu64** [real-pmein1/stmsrvemu#31]
to achieve this you'll need:
-the server computer (metal or VM works fine, must be W7 or higher)
-the target computer (for example a WXP computer)
-the emulator itself, untouched

extract the server files on the server computer and modify the emulator.conf file to edit the server ip parameter. open cmd and type `ipconfig`. find your computer's ip starting by 192.168. copy and paste that in place of the original 127.0.0.1 (loopback) ip, then save the file.
start the emulator, let it download any updates it needs and prepare a client. a firewall popup will appear, press okay and then after the client is prepare, move it into a storage medium that both computers can read, and open the steam client in the target.computer. the server should start spitting stuff and the client should be downloading files.

congrats, it works.

adding games to the emulator is something i have no idea about, so don't ask me to tell you.

**Comment by real-pmein1** [comment]
This is all contained in the readme and isn't a bug.
